USE [master]
GO
/****** Object:  Database [TourOfHeroes]    Script Date: 4/7/2020 12:27:58 PM ******/
CREATE DATABASE [TourOfHeroes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TourOfHeroes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TourOfHeroes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TourOfHeroes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TourOfHeroes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TourOfHeroes] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TourOfHeroes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TourOfHeroes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TourOfHeroes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TourOfHeroes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TourOfHeroes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TourOfHeroes] SET ARITHABORT OFF 
GO
ALTER DATABASE [TourOfHeroes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TourOfHeroes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TourOfHeroes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TourOfHeroes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TourOfHeroes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TourOfHeroes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TourOfHeroes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TourOfHeroes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TourOfHeroes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TourOfHeroes] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TourOfHeroes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TourOfHeroes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TourOfHeroes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TourOfHeroes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TourOfHeroes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TourOfHeroes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TourOfHeroes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TourOfHeroes] SET RECOVERY FULL 
GO
ALTER DATABASE [TourOfHeroes] SET  MULTI_USER 
GO
ALTER DATABASE [TourOfHeroes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TourOfHeroes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TourOfHeroes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TourOfHeroes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TourOfHeroes] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TourOfHeroes', N'ON'
GO
ALTER DATABASE [TourOfHeroes] SET QUERY_STORE = OFF
GO
USE [TourOfHeroes]
GO
/****** Object:  User [hero_worshipper]    Script Date: 4/7/2020 12:27:58 PM ******/
CREATE USER [hero_worshipper] FOR LOGIN [hero_worshipper] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[Heroes]    Script Date: 4/7/2020 12:27:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Heroes](
	[HeroId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [TourOfHeroes] SET  READ_WRITE 
GO
